### ISSUE TITLE
Feature request: Add support for multiple or multiline "custom"

### ISSUE THREAD

**Issue by noabody** [xyproto/gendesk#25]
We can work around the Keywords issue from #20 with ```--custom``` but there doesn't seem to be a way to use multiple.  Only the last is honored, and it isn't possible to inject ```\n``` to break the line into multiple parts.

Neither of these produce ```StartupWMClass``` and ```Keywords```:
```
gendesk -f -n --name=name --comment='comment' --genericname='comment' --custom='StartupWMClass=class' --custom='Keywords=this;that;' --exec=exec --icon=icon --terminal=false --categories='This;That' --startupnotify=false --pkgname=name
```
```
gendesk -f -n --name=name --comment='comment' --genericname='comment' --custom='StartupWMClass=class\nKeywords=this;that;' --exec=exec --icon=icon --terminal=false --categories='This;That' --startupnotify=false --pkgname=name
```

**Comment by xyproto** [comment]
Thanks for reporting! Supporting multiple custom lines might be a good idea.

I guess there is a crossover point where enough custom lines means that the contents should be piped directly to the `.desktop` file instead.

And `StartupWM` could have a dedicated flag.

There are many possible paths.

**Comment by noabody** [comment]
I agree.  Looking at the [specs](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys), there are 24 recognized _keys_ that can reside within the desktop file. Currently, gendesk supports 12 and one _custom_.

I believe the most common ones should be implemented, without question.  Having a multiple or multi-line _custom_ should be adequate for those remaining.

**Comment by xyproto** [comment]
The main point of `gendesk` is to keep things simple and provide a minimum of information, though. If more than the basic keys are needed, would it not be simpler to just put everything in a file instead of passing they keys as flags to `gendesk`? I guess the argument for adding all keys is the ability for packages to use `gendesk` in the same way, even if the underlying `.desktop` file format should change, or if new ways of adding desktop shortcuts should appear in the future.

**Comment by noabody** [comment]
I agree.
